apiVersion: v1
kind: Pod
metadata:
  name: nvidia-smi
spec:
  restartPolicy: Never
  containers:
    - name: nvidia-smi
      image: nvidia-smi:latest
      imagePullPolicy: Never
      command:
        - nvidia-smi
      resources:
        requests:
          cpu: "100m"
          memory: "16Mi"
        limits:
          cpu: "1"
          memory: "128Mi"
          nvidia.com/gpu: 1
