apiVersion: v1
kind: Pod
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  restartPolicy: Never
  containers:
    - name: ollama
      image: ollama:latest
      imagePullPolicy: Never
      env:
        - name: OLLAMA_MODELS
          value: /data/models
        - name: OLLAMA_HOST
          value: "0.0.0.0:11434"
      command:
        - ollama
        - serve
      resources:
        requests:
          cpu: "100m"
          memory: "1Gi"
        limits:
          cpu: "3"
          memory: "2Gi"
          nvidia.com/gpu: 1

      volumeMounts:
        - name: ollama-models
          mountPath: /data/models

  volumes:
    - name: ollama-models
      hostPath:
        path: /data/k3s/ollama/models
        type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: ollama
spec:
  selector:
    app: ollama
  ports:
    - port: 11434
      targetPort: 11434
